### ISSUE TITLE
sagpr_get_PS: error: unrecognized arguments: -ele

### ISSUE THREAD

**Issue by Dong-Shiyu** [dilkins/SOAPFAST-public#13]
When I was runnnig example 12. Application of LODE to the prediction of binding energies , I got this error. What should I do?  I just pasete the code in example 12 .I have run example 1 correctly.

**Comment by dilkins** [comment]
Hello, did you compile TENSOAP with LODE descriptor capability? Ie, when you compiled it did you use the command `make LODE`?


-------- Original message --------
From: Dong-Shiyu ***@***.***>
Date: 18/04/2022 12:59 (GMT+01:00)
To: dilkins/TENSOAP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dilkins/TENSOAP] sagpr_get_PS: error: unrecognized arguments: -ele (Issue #13)


When I was runnnig example 12. Application of LODE to the prediction of binding energies , I got this error. What should I do? I just pasete the code in example 12 .I have run example 1 correctly.

**Comment by Dong-Shiyu** [comment]
Sorry, I didn't. I've thought to make will make them all. After I compile it just now, it works . Thank you!

**Comment by Dong-Shiyu** [comment]
"The commands make or make all will compile both the python and Fortran codes. "
My English is not so good , I don't know to make will not compile LODE.
