### ISSUE TITLE
Zundel Cation Example Fails

### ISSUE THREAD

**Issue by harpaf13** [dilkins/SOAPFAST-public#16]
When executing the following line in example 2. Zundel Cation: 
`sagpr_get_kernel -z 2 -ps PS1.npy -ps0 PS0.npy -s PS1_natoms.npy -o kernel1`

I get this error
```
Traceback (most recent call last):
  File "/home/harpera/work/code/TENSOAP/bin/sagpr_get_kernel", line 109, in <module>
    main()
  File "/home/harpera/work/code/TENSOAP/bin/sagpr_get_kernel", line 103, in main
    [power,scalefac,power0,zt,use_hermiticity] = parsing.set_variable_values_kernel(args)
  File "/work/code/TENSOAP/soapfast/utils/parsing.py", line 339, in set_variable_values_kernel
    scale.append(np.load(scaling[i]))
  File "/work/code/miniconda3/envs/tensoap/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'PS1_natoms.npy'
```

I tried changing the input to:
`sagpr_get_kernel -z 2 -ps PS1.npy -ps0 PS0.npy -s PS0_natoms.npy -o kernel1` 
which calculated the kernel, but I'm not sure if this is just a typo error or an error above in the tutorial.

**Comment by dilkins** [comment]
Hi, this is a strange error - could I check that your calculation of the power spectrum didn't have any problems? If the file `PS1.npy` exists, then `PS1_natoms.npy` should also exist. If there were no problems with that calculation, could you also paste the contents of the directory please?

**Comment by harpaf13** [comment]
So I think there was an issue in the rebuilding of the power spectrum. After running
`rebuild_power_spectrum.py -lm 1 -c coords_1000.xyz -nb 20 -f PS1`
The only file that is made is `PS1.npy`

At that point the contents of the directory are:
```
PS1.npy            PS1_12.npy         PS1_16.npy         PS1_1_natoms.npy  PS1_5_natoms.npy  PS1_9_natoms.npy           zundel_11.xyz  zundel_19.xyz  zundel_9.xyz
PS1_0.npy          PS1_12_natoms.npy  PS1_16_natoms.npy  PS1_2.npy         PS1_6.npy         bkp                        zundel_12.xyz  zundel_2.xyz
PS1_0_natoms.npy   PS1_13.npy         PS1_17.npy         PS1_2_natoms.npy  PS1_6_natoms.npy  compare_predicted.py       zundel_13.xyz  zundel_3.xyz
PS1_1.npy          PS1_13_natoms.npy  PS1_17_natoms.npy  PS1_3.npy         PS1_7.npy         coords_1000.xyz            zundel_14.xyz  zundel_4.xyz
PS1_10.npy         PS1_14.npy         PS1_18.npy         PS1_3_natoms.npy  PS1_7_natoms.npy  dipole_moments_predict.py  zundel_15.xyz  zundel_5.xyz
PS1_10_natoms.npy  PS1_14_natoms.npy  PS1_18_natoms.npy  PS1_4.npy         PS1_8.npy         zundel_0.xyz               zundel_16.xyz  zundel_6.xyz
PS1_11.npy         PS1_15.npy         PS1_19.npy         PS1_4_natoms.npy  PS1_8_natoms.npy  zundel_1.xyz               zundel_17.xyz  zundel_7.xyz
PS1_11_natoms.npy  PS1_15_natoms.npy  PS1_19_natoms.npy  PS1_5.npy         PS1_9.npy         zundel_10.xyz              zundel_18.xyz  zundel_8.xyz
```

If on the otherhand I don't sparsify the data and just simply run:
`sagpr_get_PS -lm 1 -f coords_1000.xyz -o PS1`

It works fine and creates both `PS1.npy` and `PS1_natoms.npy`

**Comment by dilkins** [comment]
Ah, OK, I'd completely forgotten that this example used that script! Yes, I can see the problem now, that rebuilding presumably doesn't rebuild the `natoms` file. So, the short-term fix is to use `PS0_natoms.npy`, as you did; in the longer-term, it's probably better to change that tutorial entirely.

Could I check (apologies, it seems a bit unfair to ask you to do extra tests as a "thank you" for spotting a typo), does building the L=1 power spectrum in a single shot work? i.e.: `sagpr_get_PS -lm 1 -f coords_1000.xyz -o PS1`, or `sagpr_parallel_get_PS -nrun XXX -lm 1 coords_1000.xyz -o PS1`? (where XXX is the number of cores you want to parallelize over)

**Comment by dilkins** [comment]
Sorry, didn't mean to close it, I'll leave it open in case you have any other questions on this, please feel free to close it if you're happy everything now works as intended

**Comment by harpaf13** [comment]
Yes all works as intended, and both the `sagpr_get_PS` and `sagpr_parallel_get_PS` as written above work.
