### ISSUE TITLE
Cartesian to spherical for atomic properties

### ISSUE THREAD

**Issue by dilkins** [dilkins/SOAPFAST-public#6]
The script `cartesian_to_spherical.py` should be modified so that atomic properties can also be converted.

**Comment by Jake-Turner401** [comment]
The function seems to be working well. It takes the tensor as a property from the extended xyz format and then prints the decomposed tensor components into new properties in the file.

When trying to learn from these files I am having an issue where it loads the kernels and then just ends. Previously I had seen this issue when not specifying an atom type but this is not the case here. My input is 
sagpr_train -r 0 -reg 1e-8 -f outtest.xyz -k KER0_atomic_O.npy -p shielding_L0 -rdm 4000 -pr -c 'O'

This works when I have only one extra property after positions i.e. the file is spec:pos:shielding_l0 so maybe something to do with having multiple properties in the file?

**Comment by dilkins** [comment]
> The function seems to be working well. It takes the tensor as a property from the extended xyz format and then prints the decomposed tensor components into new properties in the file.
> 
> When trying to learn from these files I am having an issue where it loads the kernels and then just ends. Previously I had seen this issue when not specifying an atom type but this is not the case here. My input is
> sagpr_train -r 0 -reg 1e-8 -f outtest.xyz -k KER0_atomic_O.npy -p shielding_L0 -rdm 4000 -pr -c 'O'
> 
> This works when I have only one extra property after positions i.e. the file is spec:pos:shielding_l0 so maybe something to do with having multiple properties in the file?

@Jake-Turner401 that's strange -- and you can load outtest.xyz OK in python? If you run something like the following in python:

`from ase.io import read;xyz = read("outtest.xyz",":");print xyz[0].arrays`

what does it give as output? Also, does `sagpr_train` throw any error message or does it just stop? And if the latter, are there any output files created?

**Comment by Jake-Turner401** [comment]
@dilkins Yes it reads into python as you would expect creating 5 arrays of the correct dimension for each frame.

It prints no error message and just stops after loading kernels. It creates the weights output file for L=0. This contains 
![image](https://user-images.githubusercontent.com/63599281/112460990-66205c00-8d57-11eb-8a50-c355ca49d384.png)

**Comment by dilkins** [comment]
Ah, OK, if it creates a weights vector then it has done the training. How many oxygen centres are there in `outtest.xyz`?

**Comment by Jake-Turner401** [comment]
If I remember correctly it is around 4500.

**Comment by Jake-Turner401** [comment]
In fact I think I may have just have found an error. The input it was created from had line breaks between the frames which then doesnt work so only a single frame was read into outtest.xyz. Not sure why that would cause it not to run but it is something I can try tomorrow.

**Comment by dilkins** [comment]
OK, that would be it -- so the model was created using that one training point and there were none left to test it on. It definitely did the training part (as you've created a weights output file), so it all ran fine, albeit with that single point -- it just stopped when asked to make predictions because there were none to make. Let's confirm that fixing the xyz file fixes this error, in that case and then we can merge the pull request.

**Comment by Jake-Turner401** [comment]
yep that works now so its good to go :)

**Comment by dilkins** [comment]
Great, thanks @Jake-Turner401 :)
